// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgency.DataAccess.Context;

#nullable disable

namespace TravelAgency.DataAccess.Migrations.Spa
{
    [DbContext(typeof(SpaContext))]
    [Migration("20260611065620_20260611_0956-AddTourBookingFields-Spa")]
    partial class _20260611_0956AddTourBookingFieldsSpa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaBookingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpaSalonDataId")
                        .HasColumnType("int");

                    b.Property<int>("SpaSalonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpaSalonDataId");

                    b.HasIndex("SpaSalonId");

                    b.ToTable("SpaBookings");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaSalonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpaSalons");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaServiceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpaSalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpaSalonId");

                    b.ToTable("SpaServices");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaServiceImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpaServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpaServiceId");

                    b.ToTable("SpaServiceImgs");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaBookingData", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Spa.SpaSalonData", null)
                        .WithMany("Bookings")
                        .HasForeignKey("SpaSalonDataId");

                    b.HasOne("TravelAgency.Domains.Entities.Spa.SpaSalonData", "SpaSalon")
                        .WithMany()
                        .HasForeignKey("SpaSalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpaSalon");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaServiceData", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Spa.SpaSalonData", "SpaSalon")
                        .WithMany("Services")
                        .HasForeignKey("SpaSalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpaSalon");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaServiceImgData", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Spa.SpaServiceData", "SpaService")
                        .WithMany("Images")
                        .HasForeignKey("SpaServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpaService");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaSalonData", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Spa.SpaServiceData", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
