// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgency.DataAccess.Context;

#nullable disable

namespace TravelAgency.DataAccess.Migrations
{
    [DbContext(typeof(TourContext))]
    [Migration("20260510195456_FixUsers2Again")]
    partial class FixUsers2Again
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.CategoryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.DescriptionAdvanced", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TourDescriptionDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourDescriptionDataId")
                        .IsUnique();

                    b.ToTable("DescriptionAdvanced");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourDescriptionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId")
                        .IsUnique();

                    b.ToTable("Description");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourImgs");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.DescriptionAdvanced", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Tour.TourDescriptionData", "TourDescriptionData")
                        .WithOne("DescriptionAdvanced")
                        .HasForeignKey("TravelAgency.Domains.Entities.Tour.DescriptionAdvanced", "TourDescriptionDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourDescriptionData");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourData", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Tour.CategoryData", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourDescriptionData", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Tour.TourData", "Tour")
                        .WithOne("Description")
                        .HasForeignKey("TravelAgency.Domains.Entities.Tour.TourDescriptionData", "TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourImgData", b =>
                {
                    b.HasOne("TravelAgency.Domains.Entities.Tour.TourData", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.CategoryData", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourData", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("TravelAgency.Domains.Entities.Tour.TourDescriptionData", b =>
                {
                    b.Navigation("DescriptionAdvanced");
                });
#pragma warning restore 612, 618
        }
    }
}
